export { type H3KitaHtmlContext } from './context.js'
export { defineKitaHandler, type KitaRender } from './handler.js'
export { type H3HtmlResult } from './html.js'
export { h3KitaHtml, type H3KitaHtmlOptions } from './plugin.js'
export { kAutoDoctype } from './utils.js'
