packages:
  - packages/*
  - benchmarks/*
  - examples/*

catalog:
  '@fastify/formbody': ^8.0.2
  '@types/jsdom': ^27.0.0
  '@types/node': ^24.10.9
  '@types/react-dom': ^19.2.3
  '@types/react': ^19.2.9
  '@typescript/native-preview': 7.0.0-dev.20260122.2
  '@vitest/coverage-v8': ^4.0.17
  c8: ^10.1.3
  fastify-plugin: ^5.1.0
  fastify: ^5.7.1
  jsdom: ^27.4.0
  react-dom: ^19.2.3
  react: ^19.2.3
  tslib: ^2.8.1
  tsx: ^4.21.0
  typescript: ^5.9.3
  vitest: ^4.0.17
