packages:
  - packages/*
  - benchmarks/*

catalog:
  '@swc-node/register': ^1.11.1
  '@swc/helpers': ^0.5.18
  '@types/jsdom': ^27.0.0
  '@types/node': ^24.10.9
  '@types/react': ^19.2.9
  '@typescript/native-preview': latest
  '@vitest/coverage-v8': ^4.0.17
  c8: ^10.1.3
  jsdom: ^27.4.0
  react: ^19.2.3
  react-dom: ^19.2.3
  tslib: ^2.8.1
  typescript: ^5.9.3
  vitest: ^4.0.17
