packages:
  - packages/*
  - benchmarks/*
  - examples/*

# Fails if trusted package stops being trusted
trustPolicy: no-downgrade
# Ignores trust policies for packages older than a week
trustPolicyIgnoreAfter: 10080
# Minimum of 1 day before released packages can be installed
minimumReleaseAge: 1440
# no git/tarball dependencies, only from trusted registry
blockExoticSubdeps: true

catalog:
  '@types/express': ^5.0.6
  '@fastify/formbody': ^8.0.2
  '@types/jsdom': ^28.0.3
  '@types/node': ^24
  '@types/react': ^19.2.17
  '@types/react-dom': ^19.2.3
  '@typescript/native-preview': 7.0.0-dev.20260411.1
  '@vitest/coverage-v8': ^4.1.10
  c8: ^12.0.0
  express: ^5.2.1
  fastify: ^5.10.0
  fastify-plugin: ^6.0.0
  jsdom: ^30.0.0
  react: ^19.2.8
  react-dom: ^19.2.8
  tslib: ^2.8.1
  tsx: ^4.23.1
  typescript: ^6 # Cannot upgrade while TS7 doesn't ship LSP Plugins & Compiler API
  vitest: ^4.1.10
