packages:
  - packages/*
  - benchmarks/*
  - examples/*

# Fails if trusted package stops being trusted
trustPolicy: no-downgrade
# Ignores trust policies for packages older than a week
trustPolicyIgnoreAfter: 10080
# Minimum of 1 day before released packages can be installed
minimumReleaseAge: 1440
# no git/tarball dependencies, only from trusted registry
blockExoticSubdeps: true

catalog:
  '@types/express': 5.0.3
  '@fastify/formbody': 8.0.2
  '@types/jsdom': 28.0.1
  '@types/node': 24.12.2
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  '@typescript/native-preview': 7.0.0-dev.20260411.1
  '@vitest/coverage-v8': 4.1.4
  c8: 11.0.0
  express: 5.1.0
  fastify: 5.8.5
  fastify-plugin: 5.1.0
  jsdom: 29.0.2
  react: 19.2.5
  react-dom: 19.2.5
  tslib: 2.8.1
  tsx: 4.21.0
  typescript: 6.0.2
  vitest: 4.1.4
