packages:
  - 'packages/*'
  - 'benchmarks/*'

catalog:
  # TypeScript and tooling
  typescript: ^5.9.2
  tslib: ^2.8.1
  '@typescript/native-preview': latest

  # Node types
  '@types/node': ^24.10.9

  # SWC tooling
  '@swc-node/register': ^1.11.1
  '@swc/helpers': ^0.5.18

  # Testing and coverage
  c8: ^10.1.3

  # JSDOM for testing
  '@types/jsdom': ^27.0.0
  jsdom: ^27.4.0

  # React
  '@types/react': ^19.2.8
  react: ^19.2.3
  react-dom: ^19.2.3
